### ISSUE TITLE
[Maintenance] Github Repo Setting

### ISSUE THREAD

**Issue by hoonii2** [hoonii2/CI_CD#1]
## Description

- Github 초기 설정을 아래와 같이 진행합니다.
- PULL_REQUEST_TEMPLATE , .gitignore 파일을 추가, README.md 를 수정 , gitflow init 을 진행합니다.
- Spring Boot Initializr 을 통해 초기 파일을 배포합니다.

## Tasks

- [x] PULL_REQUEST_TEMPLATE 추가
- [x] .gitignore 파일 추가 
- [x] README.md 수정
- [x] gitflow init 진행
- [x] Spring Boot Initializr 파일을 Main 브랜치에 배포

## References

[Spring Boot Initializr](https://start.spring.io/)
